# Generated by Django 5.0.7 on 2024-11-23 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoodHitchApp', '0048_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.customer'),
        ),
        migrations.AddField(
            model_name='message',
            name='rider',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='FoodHitchApp.rider'),
        ),
        migrations.AddField(
            model_name='order',
            name='PaymentMethod',
            field=models.CharField(choices=[('cod', 'Cash on Delivery'), ('gcash', 'Gcash')], default='cod', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='PaymentStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disapproved', 'Disapproved')], default='Pending', max_length=12),
        ),
        migrations.AddField(
            model_name='order',
            name='ProofOfPayment',
            field=models.ImageField(blank=True, null=True, upload_to='proof_of_payment/'),
        ),
        migrations.AlterField(
            model_name='delivery',
            name='DeliveryStatus',
            field=models.CharField(choices=[('Pending', 'Pending'), ('On Transit', 'On Transit'), ('Delivered', 'Delivered'), ('Received', 'Received'), ('Cancelled', 'Cancelled')], default='Pending', max_length=50),
        ),
    ]
